config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      patch :move
    end
  end
  devise_for :users
  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  acts_as_list scope: :user
  has_rich_text :content

  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: %i[ index ]
  before_action :set_task, only: %i[ show edit update destroy move ]

  # GET /tasks or /tasks.json
  def index
    @tasks = current_user&.tasks
    @task = Task.new
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.turbo_stream
        format.html { redirect_to tasks_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@task)}_form", partial: "form", locals: { task: @task }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@task)}_form", partial: "form", locals: { task: @task }) }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@task)}_item") }
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def move
    @task.insert_at(params[:position].to_i)
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:description, :completed, :content)
    end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
          rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html,
            status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav data-controller="navbar" class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <%= link_to "Home", root_path, class: "font-semibold text-xl tracking-tight" %>
  </div>
  <div class="block lg:hidden">
    <button id="navbar-toggle" data-action="navbar#toggle" class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div data-navbar-target="collapsible" class="w-full hidden lg:block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      <% if user_signed_in? %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white" %>
      <% end %>
    </div>
    <div>
      <span class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Hello there <%= current_user ? current_user.email : "friend" %></span>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <script src="https://kit.fontawesome.com/e5838750f2.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="m-4 md:m-10">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "contents", id: "#{dom_id(task)}_form") do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-7 mb-10 flex">
    <%= form.label :description, class: "sr-only" %>
    <%= form.text_field :description, class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-0 flex-grow" %>
    <%= form.submit class: "rounded-lg ml-4 py-3 px-5 bg-teal-500 text-white font-medium cursor-pointer" %>
  </div>
  <% if action_name == "edit" %>
    <%= form.rich_text_area :content, class: "mb-5" %>
  <% end %>

<% end %>

app/views/tasks/_task.html.erb
<div id="<%= "#{dom_id(task)}_item" %>" data-id="<%= task.id %>">
  <div class="my-3 mx-2 flex justify-between">
    <%= turbo_frame_tag dom_id(task) do %>
      <div class="flex items-center">
        <%= form_with(model: task, class: "text-lg inline-block my-3", data: { controller: "tasks" }) do |f| %>
          <input type="checkbox"
              <% if task.completed %> checked <% end %>
              data-action="click->tasks#toggleCompleted"
              data-tasks-target="checkbox"
              class="mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-teal-300 h-5 w-5 rounded checked:bg-teal-500"
          >
          <%= f.hidden_field :completed, data: {tasks_target: "input"} %>
        <% end %>
        <%= link_to task.description, edit_task_path(task), class: "cursor-pointer" %>
      </div>
      <% if action_name == "show" %>
        <div>
          <%= task.content %>
        </div>
      <% end %>
    <% end %>

    <% if action_name != "show" %>
      <i class="fa-solid fa-grip-vertical sortable-handle rounded-lg pt-5 pl-5 inline-block font-medium"></i>
    <% end %>
  </div>
</div>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.append "tasks" do %>
  <%= render "task", task: @task %>
<% end %>
<%= turbo_stream.replace "#{dom_id(Task.new)}_form" do %>
  <%= render "form", task: Task.new %>
<% end %>

app/views/tasks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <%= turbo_frame_tag dom_id(@task) do %>
    <%= render "form", task: @task %>
    <div class="flex">
      <%= link_to tasks_path do %>
        <i class="fa-solid fa-arrow-left rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"></i>
      <% end %>
      <%= link_to @task, target: '_top' do %> <%# TODO: don't allow clicking through to show if has unsaved changes %>
        <i class="fa-regular fa-eye rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"></i>
      <% end %>
      <%= button_to @task, method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa-regular fa-trash-can rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"></i>
      <% end %>
    </div>
  <% end %>

</div>

app/views/tasks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block fixed right-0" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tasks</h1>
  </div>

  <% if current_user %>
    <div class="min-w-full">
      <%= render "form", task: @task %>
    </div>

    <div id="tasks" class="min-w-full divide-y" data-controller="drag" data-drag-url="/tasks/:id/move">
      <%= render @tasks %>
    </div>
  <% else %>
    <p class="py-2 px-3 bg-green-50 my-5 text-green-500">
      Please <%= link_to "sign in", new_user_session_path, class: "hover:text-green-700 underline" %> to create a task.
    </p>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New task</h1>

  <%= render "form", task: @task %>

  <%= link_to 'Back to tasks', tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tasks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block fixed top-0 right-0" id="notice"><%= notice %></p>
    <% end %>

    <%= render @task %>

  </div>
</div>